name: Publish the bot

on:
  push:
    branches-ignore:
      - "*"
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup keyfile
        env:
          KEYFILE_PASSWORD: "${{ secrets.FORTA_AGENT_KEYFILE_PASSWORD }}"
        run: |
          mkdir -p ~/.forta
          printf "${{ secrets.FORTA_AGENT_KEYFILE }}" > ~/.forta/keyfile
          jq '{"agentId": .agentId, "keyfilePassword": env.KEYFILE_PASSWORD, "keyFile": "keyfile"}' forta.config.json > ~/.forta/forta.config.json

      - name: Publish
        run: npx forta-agent publish --config ~/.forta/forta.config.json

      - name: Cleanup
        run: rm -fr ~/.forta
