name: Publish the bot

on:
  push:
    branches-ignore:
      - "*"
    tags:
      - v*
  workflow_dispatch:

env:
  DUMMY: "1"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx forta-agent info
